//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testRegexpForMailNwx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5134")]
    internal sealed partial class RegExp : global::System.Configuration.ApplicationSettingsBase {
        
        private static RegExp defaultInstance = ((RegExp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RegExp())));
        
        public static RegExp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?m)(?<=^[\\W^]*?)Added\\s(?<Added>[^\\:]+)\\:\\s+\\\"(?<NewValue>[^\\\"]+)\\\"")]
        public string PatternAdded {
            get {
                return ((string)(this["PatternAdded"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?m)(?n)(?<=^[\\W^]*?)(?<Key>[^\\:]+)\\:\\s+\\\"(?<Value>[^\\\"]+)\\\"")]
        public string PatternKeyValue {
            get {
                return ((string)(this["PatternKeyValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?m)(?<=^[\\W^]*?)Removed\\s(?<Removed>[^\\:]+)\\:\\s+\\\"(?<OldValue>[^\\\"]+)\\\"")]
        public string PatternRemoved {
            get {
                return ((string)(this["PatternRemoved"]));
            }
        }
    }
}
