/*
 * Created by SharpDevelop.
 * User: alexa_000
 * Date: 10/31/2014
 * Time: 7:15 PM
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */

namespace Tmx.Core
{
    using System;
    using System.Linq;
    using System.Xml.Linq;
    
    class Program
    {
        public static void Main(string[] args)
        {
            var testResultsImporter = new TestResultsImporter();
            // var xDoc = XDocument.Load(@"\\NJQCLIB2.nwx.local\bugs_attachments\AT_ADDITIONAL_INFORMATION\AT_RUN_2014.10.31_18.00.54\NAC_7.0\Reports\NAC\SPLab-10.SPALab.at.local\150\rdp.xml");
            // var xDoc = XDocument.Load(@"\\NJQCLIB2.nwx.local\bugs_attachments\AT_ADDITIONAL_INFORMATION\AT_RUN_2014.10.31_18.00.54\NAC_7.0\Reports\NAC\TMX_report.xml");
            // var xDoc = XDocument.Load(@"\\NJQCLIB2.nwx.local\bugs_attachments\AT_ADDITIONAL_INFORMATION\AT_RUN_2014.10.25_18.52.47\CRsuite_6.5\Reports\rdp_full.xml");
            // var xDoc = XDocument.Load(@"\\NJQCLIB2.nwx.local\bugs_attachments\AT_ADDITIONAL_INFORMATION\AT_RUN_2014.10.24_01.05.01\CRsuite_6.5\Reports\rdp_full.xml");
            var xDoc = XDocument.Load(@"\\NJQCLIB2.nwx.local\bugs_attachments\AT_ADDITIONAL_INFORMATION\AT_RUN_2014.10.24_01.05.01\CRsuite_6.5\Reports\CRsuite\TMX_report.xml");
//            var df = xDoc.Root.Name.Namespace;
//            var suites = from suite in xDoc.Descendants("suite")
//                                  where suite.Attribute("name").Value != TestData.Autogenerated
//                                  select suite;
//            var list = testResultsImporter.ImportTestSuites(suites);
            var list = testResultsImporter.ImportTestResultsFromXdocument(xDoc);
            
            Console.Write("Press any key to continue . . . ");
            Console.ReadKey(true);
        }
    }
}