/*
 * Created by SharpDevelop.
 * User: APetrovsky
 * Date: 6/3/2013
 * Time: 1:14 PM
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */

namespace xmlImportTest
{
    using System;
    using System.Linq;
    using System.Xml.Linq;
    
    class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            
            // TODO: Implement Functionality Here
            
            string fileName = @"D:\20130603\rdp.xml";
            
            XDocument doc = XDocument.Load(fileName);
            XNamespace df = doc.Root.Name.Namespace;
            var suites = from suite in doc.Descendants("suite")
                where suite.Attribute("name").Value != "autogenerated"
                select suite;
            
            foreach (var singleSuite in suites) {
                //Console.WriteLine(singleSuite);
                
                var scenarios = from scenario in singleSuite.Descendants("scenario")
                    where scenario.Attribute("name").Value != "autogenerated"
                    select scenario;
                
                foreach (var singleScenario in scenarios) {
                    
                    //Console.WriteLine(singleScenario);
                    
                    var testResults = from testResult in singleScenario.Descendants("testResult")
                        where testResult.Attribute("name").Value != "autogenerated"
                        select testResult;
                    
                    foreach (var singleTestResult in testResults) {
                        
                        Console.WriteLine(singleTestResult);
                    }
                }
            }
            
            //var results = from request in doc.Descendants("suite")//(df + "Request")
            //    //where request.Elements(df + "UniqueData").Elements(df + "UniqueNumber").Any()
             //   where request.Elements("scenario").Elements("testResult").Any()
              //  select new
                //{
                    //ordNumber = (int)request.Attribute("OrderNumber"),
                    //uniqueNumber = (decimal)request.Element(df + "UniqueData").Element(df + "UniqueNumber")
                //};
//            foreach (var result in results)
//            {
//                //Console.WriteLine("{0}-{1}", result.ordNumber, result.uniqueNumber);
//            }
            
            
            Console.Write("Press any key to continue . . . ");
            Console.ReadKey(true);
        }
    }
}