//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testWcfSvc.rnd-point
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IConfigurationService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomComparerOfItemAuditConfigurationComparerById_S26KDEMj))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomComparerOfListAuditConfigurationComparerById_S26KDEMj))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomComparerOfWebAuditConfigurationComparerById_S26KDEMj))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomComparerOfSiteAuditConfigurationComparerById_S26KDEMj))]
    public partial class ConfigurationService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public ConfigurationService()
        {
            this.Url = "http://rnd-point/_vti_bin/NetWrix/ConfigurationService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConfigurationService/SetAuditConfiguration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuditConfigurationUpdateResult SetAuditConfiguration([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AuditConfiguration configuration, bool force, [System.Xml.Serialization.XmlIgnoreAttribute()] bool forceSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AuditConfiguration removedConfiguration)
        {
            object[] results = this.Invoke("SetAuditConfiguration", new object[] {
                        configuration,
                        force,
                        forceSpecified,
                        removedConfiguration});
            return ((AuditConfigurationUpdateResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAuditConfiguration(AuditConfiguration configuration, bool force, bool forceSpecified, AuditConfiguration removedConfiguration, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetAuditConfiguration", new object[] {
                        configuration,
                        force,
                        forceSpecified,
                        removedConfiguration}, callback, asyncState);
        }
        
        /// <remarks/>
        public AuditConfigurationUpdateResult EndSetAuditConfiguration(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AuditConfigurationUpdateResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConfigurationService/SetEventServiceConfiguration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SetEventServiceConfiguration([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string configuration)
        {
            this.Invoke("SetEventServiceConfiguration", new object[] {
                        configuration});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetEventServiceConfiguration(string configuration, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SetEventServiceConfiguration", new object[] {
                        configuration}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSetEventServiceConfiguration(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IConfigurationService/GetAuditConfiguration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuditConfiguration GetAuditConfiguration()
        {
            object[] results = this.Invoke("GetAuditConfiguration", new object[0]);
            return ((AuditConfiguration)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAuditConfiguration(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAuditConfiguration", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public AuditConfiguration EndGetAuditConfiguration(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AuditConfiguration)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class AuditConfiguration
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SiteAuditConfiguration[] SiteConfigurations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class SiteAuditConfiguration : CustomComparerOfSiteAuditConfigurationComparerById_S26KDEMj
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AuditLogTrimmingRetention;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuditLogTrimmingRetentionSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SiteKey Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItemAuditOperation[] ItemOperations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ListAuditOperation[] ListOperations;
        
        /// <remarks/>
        public SecurityOperations SecurityOperations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecurityOperationsSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SiteAuditOperation[] SiteOperations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WebAuditConfiguration[] WebConfigurations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WebAuditOperation[] WebOperations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class SiteKey
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        public string WebApplicationId;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class AuditOperationStatus
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Errors;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class MonitoredItemStatus
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ObjectError;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfAuditOperationAuditOperationStatusYxoTkQPR", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfAuditOperationAuditOperationStatusYxoTkQPRKeyValueOfAuditOperationAuditOperationStatusYxoTkQPR[] Operations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfAuditOperationAuditOperationStatusYxoTkQPRKeyValueOfAuditOperationAuditOperationStatusYxoTkQPR
    {
        
        /// <remarks/>
        public AuditOperation Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuditOperationStatus Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public enum AuditOperation
    {
        
        /// <remarks/>
        SiteDeleted,
        
        /// <remarks/>
        WebAdding,
        
        /// <remarks/>
        WebDeleted,
        
        /// <remarks/>
        WebMoved,
        
        /// <remarks/>
        WebProvisioned,
        
        /// <remarks/>
        ListAdded,
        
        /// <remarks/>
        ListDeleted,
        
        /// <remarks/>
        ItemAdded,
        
        /// <remarks/>
        ItemDeleted,
        
        /// <remarks/>
        ItemUpdated,
        
        /// <remarks/>
        ItemFileConverted,
        
        /// <remarks/>
        ItemFileMoved,
        
        /// <remarks/>
        ItemCheckedIn,
        
        /// <remarks/>
        ItemCheckedOut,
        
        /// <remarks/>
        ItemUncheckedOut,
        
        /// <remarks/>
        ItemAttachmentAdded,
        
        /// <remarks/>
        ItemAttachmentDeleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class WebSiteKey
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SiteKey SiteKey;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class ListKey
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebSiteKey WebSiteKey;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class ListItemKey
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ListKey ListKey;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class AuditConfigurationItemsStatus
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfListItemKeyMonitoredItemStatusYxoTkQPR", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfListItemKeyMonitoredItemStatusYxoTkQPRKeyValueOfListItemKeyMonitoredItemStatusYxoTkQPR[] ListItemItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfListKeyMonitoredItemStatusYxoTkQPR", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfListKeyMonitoredItemStatusYxoTkQPRKeyValueOfListKeyMonitoredItemStatusYxoTkQPR[] ListItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfSiteKeyMonitoredItemStatusYxoTkQPR", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfSiteKeyMonitoredItemStatusYxoTkQPRKeyValueOfSiteKeyMonitoredItemStatusYxoTkQPR[] SiteItems;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfWebSiteKeyMonitoredItemStatusYxoTkQPR", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfWebSiteKeyMonitoredItemStatusYxoTkQPRKeyValueOfWebSiteKeyMonitoredItemStatusYxoTkQPR[] WebItems;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfListItemKeyMonitoredItemStatusYxoTkQPRKeyValueOfListItemKeyMonitoredItemStatusYxoTkQPR
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ListItemKey Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MonitoredItemStatus Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfListKeyMonitoredItemStatusYxoTkQPRKeyValueOfListKeyMonitoredItemStatusYxoTkQPR
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ListKey Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MonitoredItemStatus Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfSiteKeyMonitoredItemStatusYxoTkQPRKeyValueOfSiteKeyMonitoredItemStatusYxoTkQPR
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SiteKey Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MonitoredItemStatus Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfWebSiteKeyMonitoredItemStatusYxoTkQPRKeyValueOfWebSiteKeyMonitoredItemStatusYxoTkQPR
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebSiteKey Key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MonitoredItemStatus Value;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class AuditConfigurationUpdateResult
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuditConfigurationItemsStatus AddedConfiguration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AuditConfigurationItemsStatus RemovedConfiguration;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemAuditConfiguration))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class CustomComparerOfItemAuditConfigurationComparerById_S26KDEMj
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class ItemAuditConfiguration : CustomComparerOfItemAuditConfigurationComparerById_S26KDEMj
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItemAuditOperation[] ItemOperations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public enum ItemAuditOperation
    {
        
        /// <remarks/>
        ItemAdded,
        
        /// <remarks/>
        ItemDeleted,
        
        /// <remarks/>
        ItemUpdated,
        
        /// <remarks/>
        ItemFileConverted,
        
        /// <remarks/>
        ItemFileMoved,
        
        /// <remarks/>
        ItemCheckedIn,
        
        /// <remarks/>
        ItemCheckedOut,
        
        /// <remarks/>
        ItemUncheckedOut,
        
        /// <remarks/>
        ItemAttachmentAdded,
        
        /// <remarks/>
        ItemAttachmentDeleted,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListAuditConfiguration))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class CustomComparerOfListAuditConfigurationComparerById_S26KDEMj
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class ListAuditConfiguration : CustomComparerOfListAuditConfigurationComparerById_S26KDEMj
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItemAuditConfiguration[] ItemConfigurations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItemAuditOperation[] ItemOperations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ListAuditOperation[] ListOperations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public enum ListAuditOperation
    {
        
        /// <remarks/>
        ListAdded,
        
        /// <remarks/>
        ListDeleted,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebAuditConfiguration))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class CustomComparerOfWebAuditConfigurationComparerById_S26KDEMj
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class WebAuditConfiguration : CustomComparerOfWebAuditConfigurationComparerById_S26KDEMj
    {
        
        /// <remarks/>
        public string Id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItemAuditOperation[] ItemOperations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ListAuditConfiguration[] ListConfigurations;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ListAuditOperation[] ListOperations;
        
        /// <remarks/>
        public string ParentWebId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public WebAuditOperation[] WebOperations;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public enum WebAuditOperation
    {
        
        /// <remarks/>
        WebAdding,
        
        /// <remarks/>
        WebDeleted,
        
        /// <remarks/>
        WebMoved,
        
        /// <remarks/>
        WebProvisioned,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SiteAuditConfiguration))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public partial class CustomComparerOfSiteAuditConfigurationComparerById_S26KDEMj
    {
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public enum SecurityOperations
    {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        SecGroupCreate = 2,
        
        /// <remarks/>
        SecGroupDelete = 4,
        
        /// <remarks/>
        SecGroupMemberAdd = 8,
        
        /// <remarks/>
        SecGroupMemberDel = 16,
        
        /// <remarks/>
        SecRoleDefCreate = 32,
        
        /// <remarks/>
        SecRoleDefDelete = 64,
        
        /// <remarks/>
        SecRoleDefModify = 128,
        
        /// <remarks/>
        SecRoleDefBreakInherit = 256,
        
        /// <remarks/>
        SecRoleBindUpdate = 512,
        
        /// <remarks/>
        SecRoleBindInherit = 1024,
        
        /// <remarks/>
        SecRoleBindBreakInherit = 2048,
        
        /// <remarks/>
        All = 4096,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "4.3.3.9663-463ee024")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NetWrix.SharePoint.Audit.Services.Interfa" +
        "ces")]
    public enum SiteAuditOperation
    {
        
        /// <remarks/>
        SiteDeleted,
    }
}
