//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JdiCodeGenerator.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JdiCodeGenerator.Core.WebNames", typeof(WebNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string AttributeNameClass {
            get {
                return ResourceManager.GetString("AttributeNameClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to href.
        /// </summary>
        internal static string AttributeNameHref {
            get {
                return ResourceManager.GetString("AttributeNameHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string AttributeNameId {
            get {
                return ResourceManager.GetString("AttributeNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string AttributeNameName {
            get {
                return ResourceManager.GetString("AttributeNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        internal static string AttributeNameTag {
            get {
                return ResourceManager.GetString("AttributeNameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body.
        /// </summary>
        internal static string ElementTypeBody {
            get {
                return ResourceManager.GetString("ElementTypeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #comment.
        /// </summary>
        internal static string ElementTypeComment {
            get {
                return ResourceManager.GetString("ElementTypeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to head.
        /// </summary>
        internal static string ElementTypeHead {
            get {
                return ResourceManager.GetString("ElementTypeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html.
        /// </summary>
        internal static string ElementTypeHtml {
            get {
                return ResourceManager.GetString("ElementTypeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #text.
        /// </summary>
        internal static string ElementTypeText {
            get {
                return ResourceManager.GetString("ElementTypeText", resourceCulture);
            }
        }
    }
}
